config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/new'
  # get 'reviews/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating,  numericality: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render "new"
    end
  end

  def destroy
    
  end
  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "new"
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">
  <br>
  <%= form_for(@restaurant) do |f| %>
  <div class="form-group">
  <%= f.label :name%>
  <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :address%>
  <%= f.text_field :address, class:"form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :category%>
  <%= f.text_field :category, class:"form-control"  %>
  </div>
  <%= f.submit "add a restaurant", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<h1 class=text-center>WELCOME TO YELP</h1>
<br>
<div class="container">
  <h4><%= link_to "Add a restaurant", new_restaurant_path %></h4>
  <br>
  <% @restaurants.each do |restaurant| %>
  <h4><strong><%= link_to restaurant.name, restaurant_path(restaurant) %></strong></h4>
  <p><strong>address:</strong> <%= restaurant.address %></p>
  <p><strong>category:</strong> <%= restaurant.category %></p>
  <br>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <br>
  <%= form_for(@restaurant) do |f| %>
  <div class="form-group">
  <%= f.label :name%>
  <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :address%>
  <%= f.text_field :address, class:"form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :category%>
  <%= f.text_field :category, class:"form-control"  %>
  </div>
  <%= f.submit "add a restaurant", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
    <h1><%= @restaurant.name %></h1>
    <p><strong>Address:</strong> <%= @restaurant.address %></p>
    <p><strong>Category:</strong> <%= @restaurant.category.capitalize %></p>

    <ul>
    <% @restaurant.reviews.each do |review| %>
      <li><%= review.content %> | <%= review.rating %></li>
    <% end %>
    </ul>
    <%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>
    |
    <%= link_to "Edit", edit_restaurant_path(@restaurant) %>
    |
    <%= link_to "Home", restaurants_path %>
    |
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <br>
  <%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
  <% end %>
</div>